#!/bin/bash
source $HOME/.config/autorandr/switch_actions.sh
if ! pgrep -x "bspwm" >/dev/null
then
    exit
fi

echo $(date +'%Y-%m-%d %H:%M:%S') last profile $AUTORANDR_LAST_PROFILE >> ~/git/dotfiles/autorandr/log

if [[ $AUTORANDR_LAST_PROFILE == 'docked' ]]; then
    backup_nodes $SECONDARY_MONITOR
    move_nodes $SECONDARY_MONITOR $MAIN_MONITOR
    remove_desktops $SECONDARY_MONITOR
    bspc wm -r
fi
echo $(date +'%Y-%m-%d %H:%M:%S') undocked/postswitch >> ~/git/dotfiles/autorandr/log
