#!/bin/bash
source $HOME/.config/autorandr/switch_actions.sh
if ! pgrep -x "bspwm" >/dev/null
then
    exit
fi

echo $(date +'%Y-%m-%d %H:%M:%S') last profile $AUTORANDR_LAST_PROFILE >> $HOME/.config/autorandr/autorandr.log

if [[ $AUTORANDR_LAST_PROFILE == 'undocked' || $AUTORANDR_LAST_PROFILE == 'mirror' ]]; then
    bspc wm -r
    bspc monitor $SECONDARY_MONITOR -d $DESKTOPS 
    restore_nodes $SECONDARY_MONITOR
fi
echo $(date +'%Y-%m-%d %H:%M:%S') docked/postswitch >> $HOME/.config/autorandr/autorandr.log
