#!/bin/bash
source $HOME/.config/autorandr/switch_actions.sh

if pgrep -x "bspwm" >/dev/null
then
    bspc monitor $SECONDARY_MONITOR -d $DESKTOPS 
    restore_nodes $SECONDARY_MONITOR
    bspc wm -r
fi
