#!/bin/bash
source $HOME/.config/autorandr/switch_actions.sh

if pgrep -x "bspwm" >/dev/null
then
    bspc monitor $SECONDARY_MONITOR -d $DESKTOPS 
    restore_nodes $SECONDARY_MONITOR
    bspc wm -r
    nitrogen --force-setter=xinerama --head=0 --set-scaled $HOME/.local/share/backgrounds/geomwhite.png
    nitrogen --force-setter=xinerama --head=1 --set-scaled $HOME/.local/share/backgrounds/geomwhite.png
fi

echo $(date +'%Y-%m-%d %H:%M:%S') docked >> ~/git/dotfiles/autorandr/log
